import logging

ALEXA_APPLICATION_ID = 'ALEXA_SKILL_ID'

AWS_REGION = 'eu-west-1'
AWS_DYNAMODB_TABLE = 'DYNAMODB_TABLE'

GOOGLE_USER = 'GOOGLE_USERNAME'
GOOGLE_PASSWORD = 'GOOGLE_PASSWORD'
ANDROID_ID = '1234567890abcdef'

LOGGING_LEVEL = logging.INFO
